--HOW TO USE JOIN?

--Basic Example
-- SELECT USER_.ID,USER_.USERNAME_,USER_.NAMESURNAME,USER_.EMAIL,USER_.TELNR1,USER_.TELNR2,ADDRES.ADDRESSTEXT
-- FROM USER_
-- JOIN ADDRES ON USER_.ID=ADDRES.USERID
-- WHERE USER_.ID=1


--JOIN(INNER JOIN) KESİŞEN KÜME; VERİ GELMESİ İÇİN İKİ TABLODADA BİLGİLERİN DOLU OLMASI GEREKİR. TABLOLARDAN BİRİ BOŞSA BDİĞER DOLU OLSA BİLE KAYIT GELMEZ.
--JOIN VE INNER JOIN AYNIDR. JOIN YERİNE INNER JOIN DE YAZILABİLİR.

SELECT USER_.NAMESURNAME,ADDRES.* FROM USER_
JOIN ADDRES ON ADDRES.USERID=USER_.ID
WHERE USER_.ID=4


-- DELETE FROM USER_
-- WHERE ID=4
-- WHERE USERID=2

-- SELECT * FROM ADDRES
-- WHERE USERID=1


--LEFT JOIN

