--HOW TO USE JOIN?

--Basic Example
-- SELECT USER_.ID,USER_.USERNAME_,USER_.NAMESURNAME,USER_.EMAIL,USER_.TELNR1,USER_.TELNR2,ADDRES.ADDRESSTEXT
-- FROM USER_
-- JOIN ADDRES ON USER_.ID=ADDRES.USERID
-- WHERE USER_.ID=1


--JOIN(INNER JOIN) KESİŞEN KÜME; VERİ GELMESİ İÇİN İKİ TABLODADA BİLGİLERİN DOLU OLMASI GEREKİR. TABLOLARDAN BİRİ BOŞSA BDİĞER DOLU OLSA BİLE KAYIT GELMEZ.
--JOIN VE INNER JOIN AYNIDR. JOIN YERİNE INNER JOIN DE YAZILABİLİR.

-- SELECT USER_.NAMESURNAME,ADDRES.* FROM USER_
-- JOIN ADDRES ON ADDRES.USERID=USER_.ID
-- WHERE USER_.ID=4


-- DELETE FROM USER_
-- WHERE ID=4
-- WHERE USERID=2

-- SELECT * FROM ADDRES
-- WHERE USERID=1


--LEFT JOIN / LEFT OUTER JOIN
--Sol kümenin (eşitliğin sol tarafına yazılan tablonun) tüm satırlarını getirir. Sağ kümede karşılığı yoksa boş gösterilir.

-- SELECT USER_.NAMESURNAME,ADDRES.* FROM USER_
-- LEFT JOIN ADDRES ON ADDRES.USERID=USER_.ID
-- WHERE USER_.ID IN (100,101,102)


--RIGHT JOIN/RIGHT OUTER JOIN
--Sağ kümenin (eşitliğin sağ tarafona tablonun) tüm satırlarını getirir. Sol kümede karşılığı yoksa boş gösterilir.

-- SELECT USER_.NAMESURNAME,ADDRES.* FROM USER_
-- RIGHT OUTER JOIN ADDRES ON USER_.ID=ADDRES.USERID
-- WHERE USER_.ID IN (100,101,102)


--HOW USE ALIAS/TAKMA AD

-- SELECT U.NAMESURNAME,A.*
-- FROM USER_ U
-- LEFT JOIN ADDRES A ON A.USERID=U.ID
-- WHERE U.ID IN (100,101,102)

SELECT U.*,A.*
FROM USER_ U

JOIN ADDRES A ON U.ID=A.USERID
JOIN 

WHERE U.ID=1
