--HOW TO USE JOIN?

--Basic Example
-- SELECT USER_.ID,USER_.USERNAME_,USER_.NAMESURNAME,USER_.EMAIL,USER_.TELNR1,USER_.TELNR2,ADDRES.ADDRESSTEXT
-- FROM USER_
-- JOIN ADDRES ON USER_.ID=ADDRES.USERID
-- WHERE USER_.ID=1


--JOIN(INNER JOIN) KESİŞEN KÜME; VERİ GELMESİ İÇİN İKİ TABLODADA BİLGİLERİN DOLU OLMASI GEREKİR. TABLOLARDAN BİRİ BOŞSA BDİĞER DOLU OLSA BİLE KAYIT GELMEZ.
--JOIN VE INNER JOIN AYNIDR. JOIN YERİNE INNER JOIN DE YAZILABİLİR.

-- SELECT USER_.NAMESURNAME,ADDRES.* FROM USER_
-- JOIN ADDRES ON ADDRES.USERID=USER_.ID
-- WHERE USER_.ID=1


-- DELETE FROM USER_
-- WHERE ID=4
-- WHERE USERID=2

-- SELECT * FROM ADDRES
-- WHERE USERID=1


--LEFT JOIN / LEFT OUTER JOIN
--Sol kümenin (eşitliğin sol tarafına yazılan tablonun) tüm satırlarını getirir. Sağ kümede karşılığı yoksa boş gösterilir.

-- SELECT USER_.NAMESURNAME,ADDRES.* FROM USER_
-- LEFT JOIN ADDRES ON ADDRES.USERID=USER_.ID
-- WHERE USER_.ID IN (100,101,102)


--RIGHT JOIN/RIGHT OUTER JOIN
--Sağ kümenin (eşitliğin sağ tarafona tablonun) tüm satırlarını getirir. Sol kümede karşılığı yoksa boş gösterilir.

-- SELECT USER_.NAMESURNAME,ADDRES.* FROM USER_
-- RIGHT OUTER JOIN ADDRES ON USER_.ID=ADDRES.USERID
-- WHERE USER_.ID IN (100,101,102)


--HOW USE ALIAS/TAKMA AD
-- HEM TABLO İSİMLERİNE HEM DE SÜTUN İSİMLERİNE ALIAS ATANABİLİR. SÜTUN İSİMLERİNE ATANIRKEN ARAYA "AS" KOYULABİLİR ANCAK ŞART DEĞİLDİR.
-- ALIAS KULLANIRKEN BOŞLUK YA DA TÜRKÇE KARAKTER KULLANILAMAZ.

-- SELECT U.NAMESURNAME,A.*
-- FROM USER_ U
-- LEFT JOIN ADDRES A ON A.USERID=U.ID
-- WHERE U.ID IN (100,101,102)


-- SELECT
-- U.USERNAME_ KULLANICIADI,
-- U.NAMESURNAME ADSOYAD,
-- U.EMAIL AS EMAIL,
-- U.TELNR1 AS TELNO1,
-- U.TELNR2 AS TELNO2,
-- C.CITY AS SEHIR,
-- T.TOWN AS SEHIR,
-- D.DISTRICT AS MAHALLE,
-- A.ADDRESSTEXT AS ACIKADRES
-- FROM USER_ U

-- JOIN ADDRES A ON U.ID=A.USERID
-- JOIN CITY C ON C.ID=A.CITYID
-- JOIN TOWN T ON T.ID=A.TOWNID
-- JOIN DISTRICT D ON D.ID=A.DISTRICTID

-- WHERE U.ID=1



-- HOW TO USE GROUP BY WITH JOINS

-- HER BİR KULLANICININ KAÇ TANE ADRESİ OLDUĞUNU NASIL LİSTELERİZ? KULLANICIADI,ADSOYAD,EMAIL,TELNR1,TELNR2,KAÇ ADRESİ VAR

-- SELECT
-- U.USERNAME_ KULLANICIADI,
-- U.NAMESURNAME ADSOYAD,
-- U.EMAIL EMAIL,
-- U.TELNR1 TELNO1,
-- U.TELNR2 TELNO2,
-- COUNT(A.ID) ADRESSAYISI

-- FROM USER_ U

-- JOIN ADDRES A ON U.ID=A.USERID
-- -- WHERE U.ID=1 --ID'SİNE GÖRE SADECE BİR KİŞİNİN KAÇ ADRESİ VAR BULMA
-- GROUP BY U.USERNAME_,U.NAMESURNAME,U.EMAIL,U.TELNR1,U.TELNR2
-- -- ORDER BY COUNT(A.ID) DESC --SIRALAMA
-- HAVING COUNT(A.ID)=3 --EŞİTLİĞİN SAĞ TARAFINDAKİ SAYI KADAR OLAN KAÇ KULLANICI VAR?


-- HANGİ ŞEHİRDE KAÇ KULLANICI VAR?


-- SELECT
-- C.CITY SEHIR,COUNT(U.ID) KISISAYISI

-- FROM USER_ U
-- JOIN ADDRES A ON U.ID=A.USERID
-- JOIN CITY C ON C.ID=A.CITYID
-- JOIN TOWN T ON T.ID=A.TOWNID
-- JOIN DISTRICT D ON D.ID=A.DISTRICTID

-- GROUP BY C.CITY
-- ORDER BY KISISAYISI DESC


-- HANGİ ŞEHİRDE KAÇ KULLANICI VAR? KAÇ FARKLI ŞEHİRDE?

SELECT
U.ID,
U.USERNAME_ KULLANICIADI,
U.NAMESURNAME ADSOYAD,
U.EMAIL,
U.TELNR1 TELEFON1,
U.TELNR2 TELEFON2,
COUNT(A.ID) ADRESSAYISI,
COUNT(DISTINCT C.CITY) SEHIRSAYISI

FROM USER_ U

JOIN ADDRES A ON U.ID=A.USERID
JOIN CITY C ON C.ID=A.CITYID
JOIN TOWN T ON T.ID=A.TOWNID
JOIN DISTRICT D ON D.ID=A.DISTRICTID

GROUP BY
U.ID,
U.USERNAME_,
U.NAMESURNAME,
U.EMAIL,
U.TELNR1,
U.TELNR2

HAVING COUNT(A.ID)<>COUNT(DISTINCT C.CITY) --AYNI ŞEHİRDE BİRDEN FAZLA ADRESİ OLAN KİŞİ SAYISI

-- YUKARIDAKİNİN SAĞLAMASI
-- SELECT * FROM ADDRES WHERE USERID=4460