-- SELECT * FROM BASKET WHERE BASKET.USERID=4113
-- SELECT * FROM BASKETDETAIL WHERE BASKETDETAIL.BASKETID=1
-- SELECT * FROM PAYMENT
-- SELECT * FROM ORDER_
-- SELECT * FROM ORDERDETAIL
-- SELECT * FROM INVOICE WHERE INVOICE.ID=1
-- SELECT * FROM INVOICEDETAIL


SELECT *
FROM USER_ U
INNER JOIN BASKET B ON B.USERID=U.ID
