--Practice with New Database
-- AGGREGATE FUNCTIONS(SUM, COUNT, MIN, MAX, AVG)
-- SELECT SUN(PRICE), COUNT(ID),MIN(PRICE),MAX(PRICE,AVG(PRICE)

-- SELECT * FROM SALES
-- SELECT SUM(LINENET) FROM SALES WHERE BRANCH='Kocaeli Subesi'
-- SELECT SUM(LINENET),COUNT(*) FROM SALES WHERE BRANCH='Kocaeli Subesi'
-- SELECT SUM(LINENET),COUNT(*),MIN(LINENET),MAX(LINENET)
-- FROM SALES WHERE BRANCH='iSTANBUL Subesi'
-- SELECT SUM(LINENET) AS TOPLAMSATIS,COUNT(*) AS SATIRSAYISI,MIN(LINENET) AS ENDUSUKFIYAT,MAX(LINENET) ENYUKSEKFIYAT, AVG(LINENET) AS ORTALAMASATISFIYATI
-- FROM SALES WHERE BRANCH='iSTANBUL Subesi'

